### ISSUE TITLE
Emulator freeze during navigating in menu

### ISSUE THREAD

**Issue by mikezt** [mborik/GPMD85Emulator#11]
When I open the menu and navigate through various sub-menus, the emulator used to freeze in short time. I found it's because of the SDL_Delay calls in  MenuOpen and MenuClose routines. In attachment is a patch to eliminate this.
[menufix.txt](https://github.com/mborik/GPMD85Emulator/files/2412381/menufix.txt)

**Comment by mborik** [comment]
fixed in eabe1fe
please test for regressions, for example if key repeat working normally in menu navigation
