### ISSUE TITLE
Screen was redrawn only after menu enter and exit

### ISSUE THREAD

**Issue by jose1711** [mborik/GPMD85Emulator#13]
Changes on screen was seen only after some action in menu. For example:
- key M pressed
- nothing happen on screen
- entering a menu with `AltGr`+`F1`
- exiting from menu with `Esc`
- M showed in command prompt

Tested with current working copy in repo
Arch Linux
SDL2 v2.0.10

**Comment by mborik** [comment]
Hm, strange... It looks like an issue with processing `SDL_WINDOWEVENT_EXPOSED` event.
Can you find out if you have OpenGL support in OS?
Could you attach here full log from `./configure` & `make` process,
also all trace messages while emulator is running and you simulating your issue.

Meanwhile I will investigate an issue you should test forcing a software renderer in SDL2:
in file `/GPMD85emu.cpp` at line 72 replace `SDL_RENDERER_ACCELERATED` with `SDL_RENDERER_SOFTWARE` and recompile...

**Comment by jose1711** [comment]
This is my desktop system and it does have full OpenGL support (using Nvidia 750Ti with proprietary module). Switching to software renderer and recompiling instantly fixes the problem.

Logs from compilation (before changing line 72):
[config.log](https://github.com/mborik/GPMD85Emulator/files/3935343/config.log)
[make.log](https://github.com/mborik/GPMD85Emulator/files/3935344/make.log)

**Comment by mborik** [comment]
Great! Well, so I will add configuration parameter into `default.conf` which will force that software renderer and everyone will be able to set it by own. 👍

**Comment by jose1711** [comment]
Does it mean that the issue is likely caused by the proprietary Nvidia driver?

**Comment by mborik** [comment]
Yes, there is probably issue with that driver or some `gtkgl` adaptor, hard to say...

**Comment by jose1711** [comment]
thank you for this workaround. fwiw i have experienced the same effect while testing with raspberry pi and fake kms mode.
