### ISSUE TITLE
GPMD85Emulator v0.11.1912 beta - bugs 

### ISSUE THREAD

**Issue by zkolar75** [mborik/GPMD85Emulator#14]
**> bad, noise sound - unacceptable high tones**

**Comment by zkolar75** [comment]
**1. MENU >> EMULATOR**
- nefunkční položka " AUTO-SAVE SETTINGS "
- nefunkční položka " SAVE SETTINGS "

( ve verzi GPMD85Emulator v0.10.1801 beta - OK )

**Comment by zkolar75** [comment]
**2. zhoršená kvalita reprodukce zvuků a hudby**
    - zašuměná
    - dochází i ke spoždování

( mnohem horší než ve verzi GPMD85Emulator v0.10.1801 beta )

**Comment by zkolar75** [comment]
**3. restart app**

- občasný a samovolný restart app 
( nelze přesně specifikovat )

**Comment by zkolar75** [comment]
**4. MAIN MENU >> MEMORY**

- položka " ROM MODULE "  není  zatrhnuta ( i když  je volba nastavena v default.cfg )

**Comment by zkolar75** [comment]
**5. MAIN MENU >> PERIPHERALS >> PMD32**

- položka " CONNECTED"  není  zatrhnuta a není  funkční  ( i když  je volba nastavena v default.cfg )

**Comment by mborik** [comment]
Hi, please, check the latest commits.
