### ISSUE TITLE
Poor sound quality

### ISSUE THREAD

**Issue by zkolar75** [mborik/GPMD85Emulator#15]
Poor quality of sound and music was not fixed.

- noisy
- unpleasant high pitch tones
- unpleasant interferences
- there are some slow-downs and lags

_Originally posted by @zkolar75 in https://github.com/mborik/GPMD85Emulator/issues/14#issuecomment-564011202_

**Comment by mborik** [comment]
Please, use english and **STOP closing & reopening issues!**

**Comment by zkolar75** [comment]
OK,  waiting for Xmas ✌😈

**Comment by zkolar75** [comment]
In emulator PMD85Emu v3.1.5.204 for Windows is sound perfect 👍
.
> I will investigate an issue also on different platforms, but it's strange because previous release sounds even horrible, noisy and it's lagging all the time.



> Poor quality of sound and music was not fixed.
> 
> * noisy
> * unpleasant high pitch tones
> * unpleasant interferences
> * there are some slow-downs and lags
> 
> _Originally posted by @zkolar75 in [#14 (comment)](https://github.com/mborik/GPMD85Emulator/issues/14#issuecomment-564011202)_

**Comment by mborik** [comment]
It's different emulator, different code, different platform, different technical background. You shouldn't compare those emulators.
You know, it's very easy to criticize, creating issues but making no contribution...

**Comment by zkolar75** [comment]
OK, take it, easy,
I have been made TESTING only for errors, nothing more.
( maybe construkctive criticism )

**Comment by zkolar75** [comment]
> Poor quality of sound and music was not fixed.
> 
> * noisy
> * unpleasant high pitch tones
> * unpleasant interferences
> * there are some slow-downs and lags
> 
> _Originally posted by @zkolar75 in [#14 (comment)](https://github.com/mborik/GPMD85Emulator/issues/14#issuecomment-564011202)_

Something NEW about this issue?

**Comment by zkolar75** [comment]
**Something NEW about this?**

> I will investigate an issue also on different platforms, but it's strange because previous release sounds even horrible, noisy and it's lagging all the time.
