### ISSUE TITLE
Probably error in mapping keyboard

### ISSUE THREAD

**Issue by zkolar75** [mborik/GPMD85Emulator#16]
REPAIR
**Probably error in mapping keyboard**

- The character " : " is mapped to the same key as the character " ;  "
( After pressing this key is generated " : " , wrong )

- The key that should generate the character " : " is generates nothing.

**Comment by mborik** [comment]
thanks a lot!
fixed, please test 😉

**Comment by zkolar75** [comment]
OK, function right noW.  👌👍✌😆

> thanks a lot!
> fixed, please test
