### ISSUE TITLE
saa/Makefile.in not found

### ISSUE THREAD

**Issue by bodhi-baum** [mborik/GPMD85Emulator#18]
When trying to compile the latest source of GPMD85 0.11.1912, compiler stops, complaining that saa/Makefile.in is not found.

**Comment by mborik** [comment]
Check if you follow all steps in INSTALL.md? It looks like missing `autoreconf -vfi`

**Comment by mborik** [comment]
@bodhi-baum any update?

**Comment by bodhi-baum** [comment]
@mborik Yes, I did the same procedure again and the result remains the same as you can see here:

bodhi@Linux:~/Test/Compis/GPMD85emu$ autoreconf -vfi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:131: error: required file 'saa/Makefile.in' not found
Makefile.am:7: error: required directory ./saa does not exist
autoreconf: automake failed with exit status: 1

Before that I again checked all dependencies.

**Comment by mborik** [comment]
**Oh, I see!** 😁
It's funny, that you find that issue. At first, I don't understand why you missing Makefile in `saa` directory. I assumed (wrong) that everyone use the git repository. Now I check the release package and it not contains `saa` directory what I don't quite understand how it happened.
Now, package is fixed, but I recommend you to prefer cloning git repository for latest and working sources _(which are checked with CI automation)_.

**Comment by bodhi-baum** [comment]
Now it did compile - but where does it usually is set? I can`t start it now.
