### ISSUE TITLE
M602 mouse support

### ISSUE THREAD

**Issue by zkolar75** [mborik/GPMD85Emulator#19]
M602 mouse support is implemented ?
Thnx f Y A

**Comment by mborik** [comment]
No, it's not implemented. Probably it should be implemented (once, in future) if there will be some serious program or game released which will required it (unconditionally) and there will be some "public requirement" or something like that.

**Comment by zkolar75** [comment]
this is Public Requirement 
for games like that FUNNY FRUITS, MINESWEEPER and maybe for some adventure's game in the future.
Thnx
