### ISSUE TITLE
doesn't refresh screen in Ubuntu 22.04.4 LTS Jammy  Jellyfish

### ISSUE THREAD

**Issue by zxcygnus** [mborik/GPMD85Emulator#21]
Compiled exactly as described in INSTALL.md under paragraph ##Building. It proceded as expected, without errors and warnings.

But after launch emulator displays only black screen with status line at the bottom of window. Changing screensize doesn't help, size of screen is changing, but content stays black.

When I go to the menu with settings and then back, screen is refreshed once and content is displayed, but doesn't updating. When i tried change screensize now, screen of emulated PMD 85 was erased and stayed black again.

Sound is working, so i can blindly enter command, for example DUMP 0000 and result will be displayed after entering to the menu and return back, but will not update any further.

I did try switch Ubuntu from Wayland to XOrg, but it did not change behaviour of emulator.

I am testing it on older notebook with:
Intel Core i5-4258U with Intel graphics Haswell-ULT (8G RAM etc...)
installed Linux Kernel is 6.5.0.-35-generic...
installation of Ubuntu is almost default, i did not change anything except many installed packages from repository

![2024-06-18_screenshot_GPMD85_emulator_01](https://github.com/mborik/GPMD85Emulator/assets/48947495/4d7209fb-390b-4d0d-a7df-2beb88ee5120)

**Comment by mborik** [comment]
Hi, unfortunately this is common problem of many distros. Try run `GPMD85Emu --soft-render`. If it will work, you should preconfigure this setting with `./configure --with-soft-render`.
Let me know if it helps. 👍

**Comment by zxcygnus** [comment]
Thank you very much, it did help.

At least, now this issue can be found. I saw that option in readme, but did not realized default 3D acceleration can have this effect.
