### ISSUE TITLE
The screen only updates when I enter menu and then exit it

### ISSUE THREAD

**Issue by jose1711** [mborik/GPMD85Emulator#26]
When I start the emulator (`GPMD85emu -m 2A`) I see this:
![obrázok](https://github.com/user-attachments/assets/de5621e1-2f12-461b-8145-67edcd83faf2)
When I start typing I can hear the "clicks" but nothing shows up on the display. Then I enter menu (F-F1), exit it (Esc) and the text appears.

Tried with software renderer but the result is the same.

Arch Linux, x86_64, Xorg, nvidia drivers.

**Comment by mborik** [comment]
Duplicate issue, still repeating on crappy linux gfx drivers, see #21

**Comment by jose1711** [comment]
Ah, sorry.. I thought I used sw render but apparently not. This is a slightly confusing result of a command sequence:
```
./configure && make  # creates a default build with hw acceleration enabled (and broken for me)
./configure --with-soft-render && make  # GPMD85emu w/o options = still not working, GPMD85emu --soft-render = works
make clean && ./configure --with-soft-render && make  # GPMD85emu w/o options = works
```
